# First steps to Julia

## Comments

In [1]:
# You can leave comments on a single line using the pound/hash key

#=

For multi-line comments, 
use the '#= =#' sequence.

=#

## Variables and expressions

The assignment operator `=` binds a variable name to the data.

To see the content in the data:

- `@show exp` to show the expression and its result
- [`println(stuff)`](https://docs.julialang.org/en/v1/base/io-network/#Base.println) for regular print
- [`@printf`](https://docs.julialang.org/en/v1/stdlib/Printf/) for C-like formatted output.
- Inline display for the last expression
- A semicolon `;` at the end will suppress the output

In [2]:
# Integer, 64 bit
x = 1

1

In [3]:
# Floating-point, 64-bit
y = 1.0

1.0

In [4]:
# Complex number
z = 3 + 5im

3 + 5im

In [5]:
# Unicode names: "\alpha<tab>"
α = 3.74 

3.74

In [6]:
# Strings (Text) are surrounded by double quotes. NOT SINGLE QUOTES!
s = "Julia"

"Julia"

In [7]:
# Characters are surrounded by single quotes
c = ' '

' ': ASCII/Unicode U+0020 (category Zs: Separator, space)

In [8]:
# Fractions (rational numbers)
station = 9 + 3//4

39//4

In [9]:
# Constants will emit a warning / error if you try to change it
const theUltimateAnswer = 42

42

In [10]:
println("Hello World")
println("Hello ", s)
println(1, 2, 3)

Hello World
Hello Julia
123


In [11]:
# @show will print x = val
@show x	1+1 2-2 3*3;

x = 1
1 + 1 = 2
2 - 2 = 0
3 * 3 = 9


In [12]:
@show typeof(x) typeof(y) typeof(c)  typeof(s) typeof(z) typeof(1//2);

typeof(x) = Int64
typeof(y) = Float64
typeof(c) = Char
typeof(s) = String
typeof(z) = Complex{Int64}
typeof(1 // 2) = Rational{Int64}


In [13]:
# convert(T,x) to concert x to type T
typeof(convert(Float64, x))

Float64

In [14]:
# Often you can use Type(x)
typeof(Float64(x))

Float64

In [15]:
# Or even this convenience function
typeof(float(x))

Float64

## Compound expressions

- A [begin block](https://docs.julialang.org/en/v1/base/base/#begin) `begin` ... `end` squashes multiple expressions into one.
- A [let block](https://docs.julialang.org/en/v1/manual/variables-and-scoping/#Let-Blocks) `let` ... `end` is similar to a begin block but variables inside will be discarded outside.

In [16]:
begin
	a1 = 2
	a2 = 35
	a1 = a1 * a2
end

70

In [17]:
let
	x = 1
	y = 2
	z = 3
	
	x + y * z
end

7

# Math expressions

Julia supports basic arithmatic operations and essentail math functions by default.

## Basic arithmetic

In [18]:
# Multiple assignment
a, b = 2, 3

(2, 3)

In [19]:
a + b

5

In [20]:
a - b

-1

In [21]:
a * b

6

In [22]:
b / a

1.5

In [23]:
b // a

3//2

In [24]:
# integer division: \div<tab>`, the same as div(a, b)`
a÷b

0

In [25]:
b % a

1

In [26]:
a^b

8

## Comparison

Returns a Boolean value (`true` / `false`)

In [27]:
@show a b;

a = 2
b = 3


In [28]:
a < 1

false

In [29]:
b > 2

true

In [30]:
a <= b

true

In [31]:
a != b

true

In [32]:
a == b + 1

false

In [33]:
# Chained comparisons are supported
1 < a <= b

true

In [34]:
# Approximation operator `\approx<TAB>` for floating point number equivalence
1e10 + 1.0 ≈ 1e10

true

In [35]:
isapprox(1e10 + 1.0, 1e10)

true

## Math functions

In [36]:
sin(0.5*π)

1.0

In [37]:
cos(0.5*π)

6.123233995736766e-17

In [38]:
cospi(1//2)  # More accurate

0.0

In [39]:
sqrt(π) ≈ √π # `\sqrt<TAB>`

true

In [40]:
log(10)   # Natual log

2.302585092994046

In [41]:
log10(10) # Common log

1.0

In [42]:
exp(-5)

0.006737946999085467

In [43]:
# expm1(x) is more accurate that exp(x) - 1 when x is very small
exp(1e-12)-1, expm1(1e-12)

(1.000088900582341e-12, 1.0000000000005e-12)

# Strings

- [Think Julia ch8](https://benlauwens.github.io/ThinkJulia.jl/latest/book.html#chap08)
- [Introduction_to_Julia_tutorials](https://nbviewer.jupyter.org/github/xorJane/Introduction_to_Julia_tutorials/blob/master/02.Strings.ipynb)

A `string` is a sequence of characters.

- `" ... "` for one line strings.
- Three double quotes to surround multiline string.
- `str1*str2*...` to concatenate strings
- `string(str1, str2, ...)` to convert the data (if neede) and make a string.
- `^` to repeat a string: `str^3` to repeat `str` three times.
- `[idx]` to access an individual character.
- `$` to insert (or interpolate) a value into a string.


Although `string(x, y)` looks less streamlined, it is generally faster than interpolation `$` or concatenation `*` and is most recommended.

In [44]:
"I am a string."

"I am a string."

In [45]:
"""I am also a 
string."""

"I am also a \nstring."

In [46]:
'a' == "a"

false

In [47]:
str1 = "BEBI"

"BEBI"

In [48]:
str2 = "5009"

"5009"

In [49]:
string("The class is ", str1, '-', str2, ".")

"The class is BEBI-5009."

In [50]:
"The class is $str1-$str2."

"The class is BEBI-5009."

In [51]:
# Repeating string
str2^5

"50095009500950095009"

In [52]:
# concat string
str1*"-"*str2

"BEBI-5009"

# Control flow

- [control flow](https://docs.julialang.org/en/v1/manual/control-flow/)
- [functions](https://docs.julialang.org/en/v1/manual/functions/)


Julia programs are able to run nonlinearly by controlling its execution flow.

## Conditional statements

Compound expressions are already covered in the previous chapter: [intro to Julia](intro-to-julia.html)

### `if`/`else` block:

```julia
result = if cond1
	run_if_cond1_is_true()
elseif cond2
	run_if_cond2_is_true_and_cond1_is_false()
else
	run_if_neither_is_true()
end
```

- The `elseif` and `else` blocks are optional. `if` and `end` are mandatory.
- `if` blocks return a value. Capturing the value is optional.
- `if` blocks are "leaky", i.e. they do not introduce a local scope. (The same as Python)
- Only boolean (true / false) could be evaluated in `if` blocks. Using other types (e.g. Int) will generate an error.

### Ternary operator

`cond ? tvalue : fvalue` is eqialent to:

```julia
if cond 
	tvalue
else
	fvalue
end
```

### ifelse function

All the arguments are evaluated first in `ifelse(cond, tvalue, fvalue)`.


### short cicuit evaluation

`&&` (logical and) and `||` (logical or) operators support [short circuit evaluation](
Short-circuit evaluation - Wikipedia
https://en.wikipedia.org › wiki › Short-circuit_evaluation).

- In the expression `a && b`, the subexpression `b` is only evaluated if `a` evaluates to true.
- In the expression `a || b`, the subexpression `b` is only evaluated if `a` evaluates to false.

In [53]:
true && 1  # && evaluates and returns the second argument if the first is true

1

In [54]:
false && 1  # && otherwise returns false

false

In [55]:
score = 10

10

In [56]:
# And yes, a `if` block has a return value
response = if 80 < score <= 100
  "Good"
elseif 60 < score <= 80
  "Okay"
else
  "Uh-Oh"
end

"Uh-Oh"

## Loops

Loops are repeated evaluations.

- `while` loops are often controlled by evaluated conditions.
- `for` loops are often controlled by sequence length.


- `break`: exit the loop immediately.
- `continue`: move on to the next item / evaluation immediately.

In [57]:
## Hailstone sequence (3n+1 problem) in a while loop
n = 1025489
step = 0
while n != 1
    if iseven(n)
        n ÷= 2
    else
        n = 3n + 1
    end
    step += 1
end
step

77

In [58]:
sum = 0
m = 100
for i in 1:m
    sum += i
end
sum

5050

In [59]:
for x in 1:9
    if x == 5
        continue # jump to line #2
    elseif x >=8
        break    # jump to line #9
    end
    println(x, "^2 = ", x^2)
end

1^2 = 1
2^2 = 4
3^2 = 9
4^2 = 16
6^2 = 36
7^2 = 49


In [60]:
# Use enumerate(seq) to get a pair of idx and element
for (i, x) in enumerate(10:-1:1)
    println("xs[", i, "] = ", x)
end

xs[1] = 10
xs[2] = 9
xs[3] = 8
xs[4] = 7
xs[5] = 6
xs[6] = 5
xs[7] = 4
xs[8] = 3
xs[9] = 2
xs[10] = 1


Multiple nested for loops can be combined into a single outer loop, forming the cartesian product of its iterables.

In [61]:
for i = 'x':'z', j = '1':'3'
    println(i, j)
end

x1
x2
x3
y1
y2
y3
z1
z2
z3


# Functions

> In Julia, a function is an object that maps a tuple of argument values to a return value. 
> [Julia docs](https://docs.julialang.org/en/v1/manual/functions/)


Functions facilitate:
- Code reuse and encapsulation.
- Specializations ([Methods](https://docs.julialang.org/en/v1/manual/methods/))

- Functions are first-class objects and can be passed into a higher-order function.
- The arguments are "passed-by-sharing". Modifications to mutable argument values (such as `Arrays`) will be reflected to the caller. (Similar to Python)
- Functions that will update the arguments are named with a bang `!` by convention. (e.g. sort(arr) vs sort!(arr))
- Often only the scalar version of a function is required; for vector element-wise operations, there are broadcast (dot) syntax.
- You can write multiple function with the same name provided they have different parameter lists. Julia will choose the most apporpriate one for you.

## Standard form

In [62]:
"Mechaelis-Menton function"  # Function documentations
function mm(x, k)            # function name and parameter list
  result = x / (x +k)
  return result              # return statement is optional
end

mm

In [63]:
mm(1, 0.5)

0.6666666666666666

## One-liner form

In [64]:
mm(x) = mm(x, one(x))

mm (generic function with 2 methods)

In [65]:
mm(1)

0.5

## Anonymous functions

Often used with high-order functions e.g. `map()`

In [66]:
map(x->x^2, 1:3)

3-element Vector{Int64}:
 1
 4
 9

Use [`do` block](https://docs.julialang.org/en/v1/manual/functions/#Do-Block-Syntax-for-Function-Arguments) for long anonymous functions.

`do` block are also useful in opening files.

```julia
open("outfile", "w") do io
    write(io, data)
end
```

In [67]:
val = rand(-6:6, 10)

10-element Vector{Int64}:
 -5
 -2
 -6
  3
  5
  6
  5
 -4
  3
  0

In [68]:
map(val) do x
    if x < 0 && iseven(x)
        return 0
    elseif x == 0
        return 1
    else
        return x
    end
end


10-element Vector{Int64}:
 -5
  0
  0
  3
  5
  6
  5
  0
  3
  1

## Optional arguments

[Optional (positional) arguments](https://docs.julialang.org/en/v1/manual/functions/#Optional-Arguments) are listed after mandatory ones.

```julia
function func(a, b, c=1)
# content
end
```

And they are called with `func(a, b)` or `func(a, b, 3)`

## Keyword arguments

[Keyword arguments](https://docs.julialang.org/en/v1/manual/functions/#Keyword-Arguments) are listed after `;`

```julia
function plot(x, y; style="solid", width=1, color="black")
    ###
end
```

And they are called with `plot(x, y, width=2)` or `plot(x, y; width=2)`

In [69]:
args_kwargs(args...; kwargs...) = (args, kwargs)  # mind the semicolon ;

## See also

- [Compositing functions and pipes](https://docs.julialang.org/en/v1/manual/functions/#Function-composition-and-piping)
- [Variable argument (vararg) functions](https://docs.julialang.org/en/v1/manual/functions/#Varargs-Functions)
- [Argument destructuring](https://docs.julialang.org/en/v1/manual/functions/#Argument-destructuring)
- [Scope of variables](https://docs.julialang.org/en/v1/manual/variables-and-scoping/)

# Collections, broadcasting, and Methods
Using built-in collections is the simplest way to group and organize data.

The values in a `immutable` collection cannot be updated after its creation, while in a `mutable` collection can.

The elements in `sequential` collections are accessed by integer indices, while those in `associative` collection are accessed by keys.

## Sequential collections

General rules for sequential collections:

- 1-based indexing, as in R, MATLAB, and Fortran.
- Elements are accessed by an integer index `seq[i]` or an integer range `seq[1:2:end-1]`.
- `length(seq)` returns the total size
- Splat operator `...` passes the inner contents in the collection as positional function arguments.
- Dot syntax (e.g. a .+ b) performs element-wise  / broadcasting operations.

## Ranges

`start[:step]:end`

- Immuatable
- Sequencial
- Eheap
- Evenly-spaced numerical sequences

In [70]:
1:2:10

1:2:9

In [71]:
length(1:2:10)

5

In [72]:
dump(1:10)

UnitRange{Int64}
  start: Int64 1
  stop: Int64 10


In [73]:
range(1, 10, length=10)

1.0:1.0:10.0

In [74]:
# linspace() equivalent
LinRange(1, 10, 10)

10-element LinRange{Float64}:
 1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0

In [75]:
# pick elements by a range of indices
(1:10)[3:end]

3:10

## Tuples

- immutable
- sequential collections
- efficient for heterogenous data of various types
- stack-allocated

In [76]:
tuple(1, 'a', 3.14)

(1, 'a', 3.14)

In [77]:
(1, 'a', 3.14)

(1, 'a', 3.14)

In [78]:
t1 = (1, 2, 3)

(1, 2, 3)

In [79]:
t1[1]

1

In [80]:
t2 = (1, 'a', 3.14)

(1, 'a', 3.14)

In [81]:
dump(t2)

Tuple{Int64, Char, Float64}
  1: Int64 1
  2: Char 'a'
  3: Float64 3.14


In [82]:
tuple(t1..., t2...)   # Merging multiple tuples using ... operator

(1, 2, 3, 1, 'a', 3.14)

In [83]:
let x = 1, y = 2, z = 3
    # # Tuples could be used to swap elements
	x, y, z = z, x, y
	@show x, y, z
end;

(x, y, z) = (3, 1, 2)


In [84]:
# For returning multiple values from a function
extrema([1, 5, 6, 7, -1, -3, 0])

(-3, 7)

In [85]:
sincospi(1//2)

(1.0, 0.0)

In [86]:
neighbors(x) = x+1, x-1

neighbors (generic function with 1 method)

In [87]:
neighbors(0)

(1, -1)

## Arrays

[Arrays @ Julia docs](https://docs.julialang.org/en/v1/manual/arrays/)

`[seq...]` / `collect(seq)`

Arryas are the bread and butter for scientific computing, similar to numpy's ndarrays.

- Column-major (Fortran style) rather than row-major (C and numpy style)
- Assignments and updating may cuase unwanted editing due to memory sharing.

Some useful functions for arrays:

- `length(A)` the number of elements in A
- `ndims(A)` the number of dimensions of A
- `size(A)` a tuple containing the dimensions of A
- `size(A,n)` the size of A along dimension n
- `eachindex(A)` an efficient iterator for visiting each position in A

In [88]:
# 1D array (column vector)
x = [5, 6, 7]

3-element Vector{Int64}:
 5
 6
 7

In [89]:
# np.arange() equivalent
collect(1:10)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [90]:
zeros(2, 5, 2)

2×5×2 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [91]:
ones(2, 5)

2×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [92]:
# Uninitialized array with the same data type and dims as x
similar(x)

3-element Vector{Int64}:
 140185564304032
 140185564304080
 140185564304128

In [93]:
# np.zeros_like()
zero(x)

3-element Vector{Int64}:
 0
 0
 0

In [94]:
rand(1:6, 10)

10-element Vector{Int64}:
 2
 3
 2
 6
 1
 3
 1
 5
 2
 4

In [95]:
reshape(1:12, 3, 4)

3×4 reshape(::UnitRange{Int64}, 3, 4) with eltype Int64:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [96]:
# repeat 3x2 times
repeat([1 2; 3 4], 3, 2)

6×4 Matrix{Int64}:
 1  2  1  2
 3  4  3  4
 1  2  1  2
 3  4  3  4
 1  2  1  2
 3  4  3  4

In [97]:
# comprehension for 1D array
[i^2 for i in 1:10 if i >= 5]

6-element Vector{Int64}:
  25
  36
  49
  64
  81
 100

In [98]:
# a comprehension generating 2x3 array
[x * y for x in 1:2, y in 1:3]

2×3 Matrix{Int64}:
 1  2  3
 2  4  6

In [99]:
# casting comprehension result element type to Float64
Float64[x^2 for x in 1:4] 

4-element Vector{Float64}:
  1.0
  4.0
  9.0
 16.0

In [100]:
# a 1-element tuple containing a vector
tuple([1,2,3])

([1, 2, 3],)

In [101]:
# convert vector to tuple
Tuple([1,2,3])

(1, 2, 3)

In [102]:
# 2D array (matrix)
# space is a shorthand for hcat()
# semicolone is a shorthand for vcat()
A = [1 2 3;
     4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [103]:
A[1, 2]

2

In [104]:
length(A)

6

In [105]:
axes(A)

(Base.OneTo(2), Base.OneTo(3))

In [106]:
size(A)

(2, 3)

In [107]:
ndims(A)

2

In [108]:
transpose(A)

3×2 transpose(::Matrix{Int64}) with eltype Int64:
 1  4
 2  5
 3  6

In [109]:
A'

3×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  4
 2  5
 3  6

In [110]:
@show A x A*x;

A = [1 2 3; 4 5 6]
x = [5, 6, 7]
A * x = [38, 92]


In [111]:
b = A * x

2-element Vector{Int64}:
 38
 92

In [112]:
# Find x for Ax = b, using left division operator `/`
A\b ≈ x

true

In [113]:
# Convert A to an (1D) vector, reuses memory
vec(A)

6-element Vector{Int64}:
 1
 4
 2
 5
 3
 6

In [114]:
# Arrays are mutable (i.e. you can update the contents)
# You should make a copy if you want the original intact
A[1, 1] = 0
A

2×3 Matrix{Int64}:
 0  2  3
 4  5  6

## Associative collections

- `d[key]` accesses values by keys
- `d[key] = value` sets a key-value pair for a mutable dictionary.
- `delete!(d, key)` deletes the kay (and its partner) from a mutable dictionary.
- `keys(d)` returns a series of keys
- `values(d)` returns a series of values
- `pairs(d)` returns a series of (key => value) pairs
- `merge(d1, d2, ...)` return combinations of several dicts. `merge!(d1, d2, ...)` combine several dicts and update the first one.
- `get(d, key, default)` returns the value stored for the given key, or the given default value if no mapping for the key is present.

## Named tuples

`Namedtuples` are tuples with key-value pairs.

In [115]:
nt = (a=1, b=2, c=4)

(a = 1, b = 2, c = 4)

In [116]:
nt[1]

1

In [117]:
nt.a == nt[:a] == nt[1]

true

## Dictionaries

[Dictionaries](https://docs.julialang.org/en/v1/base/collections/#Dictionaries) are mutable mappings of `key => value`.

In [118]:
eng2sp = Dict("one" => "uno", "two" => "dos", "three" => "tres")

Dict{String, String} with 3 entries:
  "two"   => "dos"
  "one"   => "uno"
  "three" => "tres"

In [119]:
eng2sp["two"]

"dos"

In [120]:
keys(eng2sp)

KeySet for a Dict{String, String} with 3 entries. Keys:
  "two"
  "one"
  "three"

In [121]:
values(eng2sp)

ValueIterator for a Dict{String, String} with 3 entries. Values:
  "dos"
  "uno"
  "tres"

In [122]:
get(eng2sp, "one", "N/A")

"uno"

In [123]:
get(eng2sp, "four", "N/A")

"N/A"

In [124]:
haskey(eng2sp, "one")

true

In [125]:
for (k ,v) in eng2sp
    println(k, " => ", v)
end

two => dos
one => uno
three => tres


In [126]:
# Creating a dict from an arrya of tuples
Dict([('a', 1), ('c', 3), ('b', 2)])

Dict{Char, Int64} with 3 entries:
  'a' => 1
  'c' => 3
  'b' => 2

In [127]:
# Creating a Dict via a generator (similar to comprehensions)
Dict(i => i^2 for i = 1:10)

Dict{Int64, Int64} with 10 entries:
  5  => 25
  4  => 16
  6  => 36
  7  => 49
  2  => 4
  10 => 100
  9  => 81
  8  => 64
  3  => 9
  1  => 1

In [128]:
Dict(zip("abc", 1:3))

Dict{Char, Int64} with 3 entries:
  'a' => 1
  'c' => 3
  'b' => 2

# Broadcasting (Dot) syntax

[Broadcasting](https://docs.julialang.org/en/v1/manual/arrays/#Broadcasting) turns scalar operations into vector ones.

In [129]:
[1, 2, 3] .+ [4, 5, 6]

3-element Vector{Int64}:
 5
 7
 9

In [130]:
sinpi.([0.5, 1.0, 1.5, 2.0])

4-element Vector{Float64}:
  1.0
  0.0
 -1.0
  0.0

In [131]:
# Create a dictionary with a list of keys and a list of values
ks = (:a, :b, :c)
vs = (1, 2, 3)
Dict(ks .=> vs)

Dict{Symbol, Int64} with 3 entries:
  :a => 1
  :b => 2
  :c => 3

In [132]:
# logspace in julia
exp10.(LinRange(-3.0, 3.0, 50))

50-element Vector{Float64}:
    0.001
    0.0013257113655901094
    0.001757510624854793
    0.002329951810515372
    0.0030888435964774785
    0.004094915062380427
    0.005428675439323859
    0.007196856730011514
    0.009540954763499934
    0.012648552168552958
    0.016768329368110093
    0.022229964825261957
    0.029470517025518096
    ⋮
   44.98432668969444
   59.63623316594639
   79.06043210907701
  104.81131341546875
  138.9495494373136
  184.20699693267164
  244.205309454865
  323.7457542817647
  429.1934260128778
  568.9866029018293
  754.3120063354608
 1000.0

In [133]:
# Make a 9*9 multiplication table
collect(1:9) .* transpose(collect(1:9))

9×9 Matrix{Int64}:
 1   2   3   4   5   6   7   8   9
 2   4   6   8  10  12  14  16  18
 3   6   9  12  15  18  21  24  27
 4   8  12  16  20  24  28  32  36
 5  10  15  20  25  30  35  40  45
 6  12  18  24  30  36  42  48  54
 7  14  21  28  35  42  49  56  63
 8  16  24  32  40  48  56  64  72
 9  18  27  36  45  54  63  72  81

# Custom data structures

In [134]:
# struct or mutable struct
struct Point  
    x
    y
end

In [135]:
# Constructor
Point() = Point(0.0, 0.0)

Point

In [136]:
p1 = Point(1.0, 2.0)

Point(1.0, 2.0)

In [137]:
p2 = Point(-3.0, 2.0)

Point(-3.0, 2.0)

In [138]:
# Defien a method for the cutsom type
add(a::Point, b::Point) = Point(a.x + b.x, a.y + b.y)

add (generic function with 1 method)

In [139]:
add(p1, p2)

Point(-2.0, 4.0)

# Methods

[Methods @ Julia docs](https://docs.julialang.org/en/v1/manual/methods/#Methods)

You can overload the same function with different argument types / numbers.

In [140]:
func(a::Int) = a + 2
func(a::AbstractFloat) = a/2
func(a::Rational) = a/11
func(a::Complex) = sqrt(a) 
func(a, b::String) = "$a, $b"

func (generic function with 5 methods)

In [141]:
func(1)

3

In [142]:
func(3.0)

1.5

In [143]:
func(33//4)

3//4

In [144]:
func(-2 + 0im)

0.0 + 1.4142135623730951im

In [145]:
func(true, "it just works and compiles down to optimal code")

"true, it just works and compiles down to optimal code"

# Package management and dependencies

Built-in package manager: [Pkg @ Julia docs](https://docs.julialang.org/en/v1/stdlib/Pkg/)

In Pluto notebooks it is recommended to use a standalone cell for dependency management. See **Appendix** for details.

In regular environments `Project.toml` and `Manifest.toml` describe the dependencies.

## Install packages

In the Julia script

```julia
using Pkg

# Function form
Pkg.add("Plots")

# Or use Pkg's special strings
pkg"add Plots"
```


In the Julia REPL:

```julia-repl
] add Plots
```

## See what are installed

```julia
using Pkg
Pkg.status()

# Or
pkg"st" # pkg"status"

```

In the Julia REPL:

```julia-repl
] st
```

## Remove packages

```julia
using Pkg
Pkg.remove("Plots")

# Or
pkg"rm Plots"
```

```julia-repl
] rm Plots
```

## Update installed packages

```julia
using Pkg
Pkg.update()

# Or
pkg"up" # pkg"update"
```

## Create / Use a environment

```julia

using Pkg

# Activate environment in the foldername directory
Pkg.activate("foldername")

# Or
pkg"activate foldername"

# Activate the current working directory
Pkg.activate(".")

# Or
pkg"activate .
```

# See also

- [Fall in love with Julia](https://nbviewer.jupyter.org/github/schlichtanders/fall-in-love-with-julia/blob/master/01%20introduction%20-%2001%20getting%20started.ipynb) notebooks.